"""
Django settings for ecomstore project.

Generated by 'django-admin startproject' using Django 1.11.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os


CURRENT_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__))).replace('\\', '/')

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'dgxre86##j$f7w^dta3@2nnkqgac^wxw#ereysptc@#$x*i^yc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','127.0.0.1']

# Change to true before deploying into production
ENABLE_SSL = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
	'django.contrib.sites',
	'utils',
	'catalog',
	'cart',
	'checkout',
	'accounts',
	'search',
	'stats',
	'tagging',
	'marketing',
	'billing',
	'caching',
	'django.contrib.sitemaps',
	'django.contrib.redirects',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'django.contrib.flatpages',
	#'raven.contrib.django.raven_compat',
	
]

MIDDLEWARE = [
	#'raven.contrib.django.raven_compat.middleware.SentryResponseErrorIdMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
	#'marketing.urlcanon.URLCanonicalizationMiddleware',
	'django.contrib.redirects.middleware.RedirectFallbackMiddleware',
	#'django.contrib.csrf.middleware.CsrfMiddleware',
	#'ecomstore.SSLMiddleware.SSLRedirect',
]

ROOT_URLCONF = 'ecomstore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
				os.path.join(BASE_DIR, 'templates'),
				os.path.join(CURRENT_PATH, 'templates'),
				],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
				'utils.context_processors.ecomstore',
				'django.template.context_processors.media',
				#'django.core.context_processors.i18n',
				#'django.core.context_processors.media',
            ],
			'libraries' :{
				'catalog_tags': 'catalog.templatetags.catalog_tags',
			}
			
        },
    },
]

#WSGI_APPLICATION = 'ecomstore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ecomstore',
		'USER': 'username',
		'PASSWORD': 'password',
		'HOST': '',
		'PORT': '',
	}
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_URL = '/static/'
STATIC_ROOT ='/STATIC_ROOT/'
#MEDIA_ROOT = [os.path.join(BASE_DIR, 'media')]
#MEDIA_URL = '/media/'

SITE_ID = 1 

SITE_NAME = 'Modern Musician'
META_KEYWORDS = 'Music, instruments, music accessories, musician supplies'
META_DESCRIPTION = 'Modern Musician is an online supplier of instruments, sheet music, and other accessories for musicians'

GOOGLE_CHECKOUT_MERCHANT_ID = 'your id here'
GOOGLE_CHECKOUT_MERCHANT_KEY = 'your key here'
GOOGLE_CHECKOUT_URL = 'https://sandbox.google.com/checkout/api/v2/merchantCheckout/Merchant/' + GOOGLE_CHECKOUT_MERCHANT_ID

AUTHNET_POST_URL = 'test.authorize.net'
AUTHNET_POST_PATH = '/gateway/transact.dll'
AUTHNET_LOGIN = ['your login here']
AUTHNET_KEY = ['your transaction key here']
	
LOGIN_REDIRECT_URL = '/accounts/my_account/'

AUTH_PROFILE_MODULE = 'accounts.userprofile'
PRODUCTS_PER_PAGE = 12
PRODUCTS_PER_ROW = 4

CANON_URL_HOST = 'www.django-ecommerce.com'
CANON_URLS_TO_REWRITE = ['django-ecommerce.com', 'modernmusician.com']

SESSION_AGE_DAYS = 90
SESSION_COOKIE_AGE = 60 * 60 * 24 * SESSION_AGE_DAYS
CACHE_BACKEND = "memcached://127.0.0.1:11211/"
# seconds to keep items in the cache
CACHE_TIMEOUT = 60 * 60

try:
	from settings_local import *
except ImportError:
	pass