# Generated by Django 2.0.4 on 2018-08-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180827_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_caption',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
