# Generated by Django 2.0.4 on 2018-08-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180827_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_caption',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
