# Generated by Django 2.0.4 on 2018-08-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchterm_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchterm',
            name='tracking_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
